id: IBDD139B2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:31:24+00:00'
last_modified: '2022-06-07T14:52:43.999360+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5387
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོ་ལས་བརྩམས་ཏེ་ལྷའི་ཟླ་བས་དྲིས་པའི་ལན་གསང་བའི་གཏེར་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E196:
      image_group_id: I3CN5389
      title: ''
      total_pages: 98
      order: 1
      base_file: E196.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
