id: P001710
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:15:59.374754
source_metadata:
  id: bdr:W3CN5387
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོ་ལས་བརྩམས་ཏེ་ལྷའི་ཟླ་བས་དྲིས་པའི་ལན་གསང་བའི་གཏེར་མཛོད།
  author: ''
  volumes:
    06e41d8df3ff433c8a02960e82f83df7:
      image_group_id: I3CN5389
      title: ''
      volume_number: 1
      total_pages: 98
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
