id: P001710
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5387
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོ་ལས་བརྩམས་ཏེ་ལྷའི་ཟླ་བས་དྲིས་པའི་ལན་གསང་བའི་གཏེར་མཛོད།
  author: ''
  volumes:
    06e41d8df3ff433c8a02960e82f83df7:
      image_group_id: I3CN5389
      title: ''
      volume_number: 1
      total_pages: 98
      base_file: v001.txt
